name: QCI/5QI Analysis Pipeline

on:
  pull_request:
    paths:
      - 'scripts/**'
      - 'configs/**'
      - 'analysis/**'
      - 'samples/**'
      - 'requirements*.txt'
  push:
    paths:
      - 'scripts/**'
      - 'configs/**'
      - 'analysis/**'
      - 'samples/**'
      - 'requirements*.txt'

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          requirements-dev.txt
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        if [ -f requirements-dev.txt ]; then
          pip install -r requirements-dev.txt
        fi
    
    - name: Run smoke test on samples
      run: |
        python scripts/analyze_qos.py \
          --input-dir samples \
          --output-dir samples/output \
          --mapping configs/qci_5qi_map.yaml \
          --window 5min \
          --verbose
    
    - name: Archive analysis outputs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: analysis-outputs-py${{ matrix.python-version }}
        path: |
          samples/output/REPORT.md
          samples/output/images/*.png
          samples/output/artifacts/*.csv
          samples/output/run.log
        retention-days: 7
    
    - name: Run tests
      run: pytest -v